# Generated by Django 5.0.1 on 2024-01-26 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_song_rename_title_album_name_alter_album_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="app.album",
            ),
            preserve_default=False,
        ),
    ]
